### PR TITLE
add CI tests for Qemu's microvm

### PR DESCRIPTION
**Pull request by stlankes**
Qemu's microvm is a machine type inspired by Firecracker and constructed after its machine model

More information are published at https://qemu.readthedocs.io/en/latest/system/i386/microvm.html

### CODE REVIEW

**Comment by stlankes** [comment]
@mkroening @jbreitbart If I am using a microVM, I am not able to shutdown by ACPI. Instead ACPI, I use a crate to send an exit command to Qemu. However, I am not able to return 0 because this is a requirement of Qemu. Currently, I return 1 on success. Do you see a better solution for my test script?

**Comment by mkroening** [comment]
Ah, nevermind. `qemu-exit` does some shifting, so 1 as success results in 1 as output. Unfortunately, failure also results as 1 as output, so we need to change that. Regarding the script, I can get it working, it seems.

**Comment by mkroening** [comment]
https://github.com/stlankes/libhermit-rs/pull/34 should fix it.

**Comment by stlankes** [comment]
@mkroening 👍

**Pull request merged**
