### PR TITLE
Minimize casts to pointers

### PR DESCRIPTION
**Pull request by cagatay-y**
Minimize casts to pointers by using:
- pointer formatting,
- from_exposed_addr{,_mut},
- from_{ref,mut} (solves #793),
- as_str
- and some other methods.

### CODE REVIEW

**Comment by mkroening** [comment]
CI failure is being fixed in https://github.com/hermit-os/kernel/pull/965.

**Comment by mkroening** [comment]
Thanks a lot! :)

Could you rebase on main instead of merging main? I'd like to avoid merge commits in feature branches.

Also, it would be great if you could have the CI run all of these commits. I usually do that by force pushing the first commit of the feature branch and then pushing commit by commit. Something like `git push origin HEAD~10:cast-elimination --force` should work (`--force` can be omitted on all but the first push).

I can also recomment `git-interactive-rebase-tool`, but any editor of your choice works just as well for rebases.

**Comment by mkroening** [comment]
Awesome. You also don't need to be up to date with main and rebase on every change, but having a green CI everywhere would be great. :)

**Comment by cagatay-y** [comment]
> As a side note, you don't have to wait for CI to finish before pushing the next commit. :)

I completely misread this message the first time and thought that you said I _have to_ wait :) Thanks for the tip!

**Comment by mkroening** [comment]
I did cancel the CI runs starting from the first unsuccessful one, so this does not block the CI. I think, you should be able to do that too if rights are configured correctly: https://github.com/hermit-os/kernel/actions

**Review by mkroening — APPROVED** [review]
Perfect! 👌 

Thanks a lot! :)

**Pull request merged**
